[2023-03-21T14:29:13.575+0000] {processor.py:153} INFO - Started process (PID=13070) to work on /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:29:13.590+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/load_csv copy.py for tasks to queue
[2023-03-21T14:29:13.600+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:29:13.598+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:29:15.054+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:29:15.052+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-21T14:29:15.071+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:29:15.096+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:29:15.096+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-21T14:29:15.167+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:29:15.166+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to 2023-03-21T00:00:00+00:00, run_after=2023-03-22T00:00:00+00:00
[2023-03-21T14:29:15.248+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/load_csv copy.py took 1.689 seconds
[2023-03-21T14:29:45.470+0000] {processor.py:153} INFO - Started process (PID=13127) to work on /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:29:45.475+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/load_csv copy.py for tasks to queue
[2023-03-21T14:29:45.482+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:29:45.481+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:29:46.337+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:29:46.334+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-21T14:29:46.353+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:29:46.486+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:29:46.485+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-21T14:29:46.547+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:29:46.547+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to 2023-03-21T00:00:00+00:00, run_after=2023-03-22T00:00:00+00:00
[2023-03-21T14:29:46.745+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/load_csv copy.py took 1.284 seconds
[2023-03-21T14:30:17.427+0000] {processor.py:153} INFO - Started process (PID=13184) to work on /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:30:17.432+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/load_csv copy.py for tasks to queue
[2023-03-21T14:30:17.442+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:30:17.441+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:30:18.363+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:30:18.361+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-21T14:30:18.377+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:30:18.417+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:30:18.417+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-21T14:30:18.465+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:30:18.465+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to 2023-03-21T00:00:00+00:00, run_after=2023-03-22T00:00:00+00:00
[2023-03-21T14:30:18.500+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/load_csv copy.py took 1.092 seconds
[2023-03-21T14:30:48.859+0000] {processor.py:153} INFO - Started process (PID=13243) to work on /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:30:48.864+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/load_csv copy.py for tasks to queue
[2023-03-21T14:30:48.868+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:30:48.868+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:30:49.484+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:30:49.482+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-21T14:30:49.495+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:30:49.517+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:30:49.516+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-21T14:30:49.561+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:30:49.561+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to 2023-03-21T00:00:00+00:00, run_after=2023-03-22T00:00:00+00:00
[2023-03-21T14:30:49.596+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/load_csv copy.py took 0.743 seconds
[2023-03-21T14:31:19.708+0000] {processor.py:153} INFO - Started process (PID=13300) to work on /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:31:19.712+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/load_csv copy.py for tasks to queue
[2023-03-21T14:31:19.716+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:31:19.715+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:31:20.495+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:31:20.483+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-21T14:31:20.512+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:31:20.540+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:31:20.539+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-21T14:31:20.592+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:31:20.592+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to 2023-03-21T00:00:00+00:00, run_after=2023-03-22T00:00:00+00:00
[2023-03-21T14:31:20.627+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/load_csv copy.py took 0.929 seconds
[2023-03-21T14:31:50.806+0000] {processor.py:153} INFO - Started process (PID=13355) to work on /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:31:50.820+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/load_csv copy.py for tasks to queue
[2023-03-21T14:31:50.837+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:31:50.835+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:31:52.716+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:31:52.711+0000] {abstractoperator.py:185} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 183, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_tables.sql
[2023-03-21T14:31:52.731+0000] {processor.py:753} INFO - DAG(s) dict_keys(['batch_pipeline']) retrieved from /opt/airflow/dags/load_csv copy.py
[2023-03-21T14:31:52.870+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:31:52.869+0000] {dag.py:2693} INFO - Sync 1 DAGs
[2023-03-21T14:31:52.924+0000] {logging_mixin.py:137} INFO - [2023-03-21T14:31:52.924+0000] {dag.py:3444} INFO - Setting next_dagrun for batch_pipeline to 2023-03-21T00:00:00+00:00, run_after=2023-03-22T00:00:00+00:00
[2023-03-21T14:31:52.966+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/load_csv copy.py took 2.172 seconds
